apiVersion: v1
kind: ConfigMap
metadata:
  name: car-rental-config
  namespace: car-rental
  labels:
    app: car-rental-app
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
