apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-app-temp
  namespace: car-rental
  labels:
    app: car-rental-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-rental-app
  template:
    metadata:
      labels:
        app: car-rental-app
    spec:
      automountServiceAccountToken: false
      containers:
      - name: car-rental-app
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "256Mi"
            cpu: "200m"
            ephemeral-storage: "2Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullPolicy: Always
