apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-app
  namespace: car-rental
  labels:
    app: car-rental-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: car-rental-app
  template:
    metadata:
      labels:
        app: car-rental-app
    spec:
      automountServiceAccountToken: false
      containers:
      - name: car-rental-app
        image: sbacrtest123.azurecr.io/car-rental:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: DOTNET_gcServer
          value: "0"
        - name: DOTNET_GCHeapCount
          value: "2"
        - name: DOTNET_GCConserveMemory
          value: "9"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "512Mi"
          limits:
            memory: "256Mi"
            cpu: "300m"
            ephemeral-storage: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
