apiVersion: v1
kind: Service
metadata:
  name: car-rental-service
  namespace: car-rental
  labels:
    app: car-rental-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: car-rental-app
  sessionAffinity: None
